"""add workspace_id to tasks

Revision ID: b749c33c96ec
Revises: 4faff2601483
Create Date: 2026-08-10 20:17:09.912358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b749c33c96ec'
down_revision: Union[str, Sequence[str], None] = '4faff2601483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('workspace_id', sa.String(), nullable=True))
    op.create_index('ix_tasks_workspace_id', 'tasks', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_workspace_id', table_name='tasks')
    op.drop_column('tasks', 'workspace_id')
    # ### end Alembic commands ###
